[build.env]
passthrough = [
  "CFLAGS",
  "TARGET",
  "RUST_TARGET",
  "BUILD_TARGET",
  "CARGO_BUILD_TARGET",
  "TARGET_CFLAGS",
  "RUSTFLAGS",
  "RUST_BACKTRACE",
  "RUST_DEBUG",
  "RUST_LOG",
  "ARCH",
  "FEATURES",
  "ROARING_ARCH",
  "TARI_NETWORK",
  "TARI_TARGET_NETWORK",
  "TARI_NETWORK_DIR",
]

[target.x86_64-linux-android]
image = "ghcr.io/cross-rs/x86_64-linux-android:edge"
pre-build = [ """
export DEBIAN_FRONTEND=noninteractive && \
apt-get update && \
apt-get --assume-yes --no-install-recommends install \
 curl unzip && \
curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v26.1/protoc-26.1-linux-x86_64.zip && \
unzip -o protoc-26.1-linux-x86_64.zip -d /usr/ && \
/usr/bin/protoc --version
""" ]

[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android:edge"
pre-build = [ """
export DEBIAN_FRONTEND=noninteractive && \
apt-get update && \
apt-get --assume-yes --no-install-recommends install \
 curl unzip && \
curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v26.1/protoc-26.1-linux-x86_64.zip && \
unzip -o protoc-25.2-linux-x86_64.zip -d /usr/ && \
/usr/bin/protoc --version
""" ]

[target.aarch64-unknown-linux-gnu]
#image = "ubuntu:18.04"
# Translates to `ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge`
#image = ":edge"
#image = ":local"
#image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"
image.name = ":edge"
#image.toolchain = ["linux/arm64=aarch64-unknown-linux-gnu"]
image.toolchain = ["linux/arm64=aarch64-unknown-linux-gnu"]
pre-build = "./scripts/cross_compile_hack.sh"

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  "CARGO_BUILD_TARGET",
  "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc",
  "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc",
  "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++",
  "PKG_CONFIG_SYSROOT_DIR=/usr/lib/aarch64-linux-gnu",
  "BINDGEN_EXTRA_CLANG_ARGS=--sysroot /usr/aarch64-linux-gnu/include/",
]

[target.x86_64-unknown-linux-gnu]
image = "ubuntu:18.04"
pre-build = "./scripts/cross_compile_hack.sh"

[target.x86_64-unknown-linux-gnu.env]
passthrough = [
  "CARGO_BUILD_TARGET",
  "CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc",
  "CC_x86_64_unknown_linux_gnu=x86_64-linux-gnu-gcc",
  "CXX_x86_64_unknown_linux_gnu=x86_64-linux-gnu-g++",
  "PKG_CONFIG_SYSROOT_DIR=/usr/lib/x86_64-linux-gnu",
  "BINDGEN_EXTRA_CLANG_ARGS=--sysroot /usr/include/x86_64-linux-gnu/"
]
