[target.x86_64-linux-android.env]
passthrough = ["CFLAGS"]

[target.aarch64-linux-android.env]
passthrough = ["CFLAGS"]

[target.arm-linux-androideabi.env]
passthrough = ["CFLAGS"]

[target.aarch64-unknown-linux-gnu]
image = "ubuntu:18.04"
pre-build = [
  """
cat << EOF > /etc/apt/sources.list.d/sources-ports-arm64.list
deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports bionic main restricted
deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports bionic-updates main restricted
deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports bionic universe
deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports bionic-updates universe
deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports bionic multiverse
deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports bionic-updates multiverse
deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports bionic-backports main restricted universe multiverse
EOF
apt-get update
dpkg --add-architecture arm64
apt-get update
apt-get install --assume-yes cmake gcc clang-10 pkg-config-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu libssl-dev:arm64
  """
]
#linker = "aarch64-linux-gnu-gcc"
#binutils-arm-linux-
#toolchain = ["aarch64-unknown-linux-gnu"]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  "CFLAGS",
  "RUST_DEBUG",
  "RUSTFLAGS=-C target_cpu=generic -C linker=/usr/bin/aarch64-linux-gnu-gcc",
#  "RUSTFLAGS=-C target_cpu=generic -C linker=aarch64-unknown-linux-gnu",
  "ARCH=aarch64",
  "FEATURES=safe",
  "ROARING_ARCH=generic",
  "BUILD_TARGET=aarch64-unknown-linux-gnu/",
  "CARGO_BUILD_TARGET=aarch64-unknown-linux-gnu",
  "TARGET=aarch64-unknown-linux-gnu",
  "RUST_TARGET=--target=aarch64-unknown-linux-gnu",
  "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc",
  "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc",
  "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++",
  "BINDGEN_EXTRA_CLANG_ARGS=--sysroot /usr/aarch64-linux-gnu/include/",
  "OPENSSL_INCLUDE_DIR=/usr/include/aarch64-linux-gnu/",
  "OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu",
]
