[build.env]
passthrough = [
  "CFLAGS",
  "TARGET",
  "RUST_TARGET",
  "BUILD_TARGET",
  "CARGO_BUILD_TARGET",
  "TARGET_CFLAGS",
  "RUSTFLAGS",
  "RUST_BACKTRACE",
  "RUST_DEBUG",
  "RUST_LOG",
  "ARCH",
  "FEATURES",
  "ROARING_ARCH",
  "TARI_NETWORK",
  "TARI_TARGET_NETWORK",
  "TARI_NETWORK_DIR",
]

[target.x86_64-linux-android]
image = "ghcr.io/cross-rs/x86_64-linux-android:edge"
pre-build = [ """
export DEBIAN_FRONTEND=noninteractive && \
apt-get update && \
apt-get --assume-yes --no-install-recommends install \
 curl unzip && \
curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v26.1/protoc-26.1-linux-x86_64.zip && \
unzip -o protoc-26.1-linux-x86_64.zip -d /usr/ && \
/usr/bin/protoc --version
""" ]

[target.x86_64-linux-android.env]
passthrough = [
  "CFLAGS=-DMDB_USE_ROBUST=0",
]

[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android:edge"
pre-build = [ """
export DEBIAN_FRONTEND=noninteractive && \
apt-get update && \
apt-get --assume-yes --no-install-recommends install \
 curl unzip && \
curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v26.1/protoc-26.1-linux-x86_64.zip && \
unzip -o protoc-26.1-linux-x86_64.zip -d /usr/ && \
/usr/bin/protoc --version
""" ]

[target.aarch64-linux-android.env]
passthrough = [
  "CFLAGS=-DMDB_USE_ROBUST=0",
]

[target.aarch64-unknown-linux-gnu]
image = "ubuntu:18.04"
# Need to use native aarch64 on Apple silicon
#image.name = "ubuntu:18.04"
#image.toolchain = ["linux/arm64=aarch64-unknown-linux-gnu"]
pre-build = "./scripts/cross_compile_ubuntu_18-pre-build.sh"

[target.x86_64-unknown-linux-gnu]
image = "ubuntu:18.04"
pre-build = "./scripts/cross_compile_ubuntu_18-pre-build.sh"
