---
name: Build libwallet on-demand - Test

on:
  push:
    branches:
      - "libwallet-*"
      - "build-leet-*"
    tags:
      - "libwallet-*"
  schedule:
    - cron: "05 00 * * *"
  workflow_dispatch:
    inputs:
      toolchain:
        type: string
        required: true
        default: 'nightly-2022-05-01'
        description: 'Rust toolchain'
      tags:
        type: string
        description: 'On-demand build description'

env:
  toolchain_default: nightly-2022-05-01

jobs:
  builds_run:
    uses: leet4tari/tari/.github/workflows/build_libwallet.yml@build-leet-testnet-dibbler-libwallet-test
    with:
      toolchain: ${{ inputs.toolchain }}

  libwallet_uploads:
    needs: builds_run
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          path: libwallet

      - name: Debugging
        shell: bash
        run: ls -alhtR
        working-directory: libwallet
