---
name: Build docker images - Test

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "build-leet-*"
  schedule:
    - cron: "05 00 * * *"
  workflow_dispatch:
    inputs:
      toolchain:
        type: string
        description: 'Rust toolchain'
      version:
        type: string
        description: 'build tag/version'
      tag_alias:
        type: string
        description: 'build tag alias'
      platforms:
        description: 'Docker build platform(s)'
        default: linux/amd64
        required: true
        type: choice
        options:
        - linux/amd64
        - linux/arm64
        - linux/arm64, linux/amd64

env:
  toolchain_default: nightly-2022-05-01

jobs:
  envs_setup:
    runs-on: ubuntu-latest
    outputs:
      toolchain: ${{ steps.set_toolchain.outputs.toolchain }}

    steps:
      - name: Set toolchain
        id: set_toolchain
        run: |
          if [ -z "${{ inputs.toolchain }}" ]; then
            echo "Using default"
            btoolchain=${{ env.toolchain_default }}
          else
            echo "Using provided input"
            btoolchain=${{ inputs.toolchain }}
          fi
          echo "Rust toolchain - ${btoolchain} ."
          echo "toolchain=${btoolchain}" >> $GITHUB_ENV

  builds_run:
    uses: ./.github/workflows/build_dockers_workflow.yml
    secrets: inherit
    with:
      toolchain: ${{ needs.envs_setup.outputs.toolchain }}
      platforms: ${{ inputs.platforms }}
      version: ${{ inputs.version }}
      tag_alias: ${{ inputs.tag_alias }}
