---
name: Build docker images on-demand

on:
  workflow_call:
    secrets:
      DOCKER_PROVIDER:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
    inputs:
      toolchain:
        type: string
        description: 'Rust toolchain'
        default: nightly-2022-05-01
      arch:
        type: string
        default: x86-64
      features:
        type: string
        default: safe
      version:
        type: string
        description: 'build tag/version'
      tag_alias:
        type: string
        description: 'build tag alias'
      image_name:
        type: string
        default: tari_sha3_miner
      app_name:
        type: string
        default: sha3_miner
      app_exec:
        type: string
        default: tari_miner
      dockercontext:
        type: string
        default: tari
      dockerfile:
        type: string
        default: tarilabs
      platforms:
        type: string
        default: linux/amd64
        # linux/arm64, linux/amd64

jobs:
  docker_build:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest

    steps:
      - name: checkout tari
        uses: actions/checkout@v3
        with:
          path: tari
          submodules: recursive

      - name: checkout tari-launchpad
        uses: actions/checkout@v3
        with:
          # repository: tari-project/tari-launchpad
          repository: leet4tari/tari-launchpad
          ref: build-leet-tari-test-cache
          path: tari-launchpad

      - name: environment setup
        shell: bash
        run: |
          mkdir -p tari/buildtools/docker_rig
          cp -v tari-launchpad/docker_rig/start_tari_app.sh tari/buildtools/docker_rig/start_tari_app.sh
          if [ -z "${{ inputs.version }}" ]; then
            TARI_SOURCE_ROOT="tari/"
            VAPP=$(awk -F ' = ' \
              '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' \
              "${TARI_SOURCE_ROOT}/applications/tari_base_node/Cargo.toml")

            VBRANCH=$(git --git-dir ${TARI_SOURCE_ROOT}/.git branch --show-current)
            VSHA_SHORT=$(git --git-dir ${TARI_SOURCE_ROOT}/.git rev-parse --short HEAD)
            bversion="v${VAPP}_${VBRANCH}_$(date -u '+%Y%m%d')_${VSHA_SHORT}"
          else
            bversion=${{ inputs.version }}
          fi
          echo "Setting ${bversion} as docker tag"
          #echo "::set-output name=version::$bversion"
          echo "version=${bversion}" >> $GITHUB_ENV
          if [ ! -z "${{ inputs.tag_alias }}" ]; then
            echo "Setup tag_alias"
            echo "::set-output name=tag_alias::${{ secrets.DOCKER_PROVIDER }}/${{ secrets.DOCKER_REPO }}/${{ inputs.image_name }}:${{ inputs.tag_alias }}"
          fi

      - name: Login to Docker Image Provider
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_PROVIDER }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU for Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: debug environment setup
        shell: bash
        run: |
          echo "Debug"
          echo ${{ env.version }}
          echo "Done"

      - name: Docker image build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./${{ inputs.dockercontext }}/
          file: ./tari-launchpad/docker_rig/${{ inputs.dockerfile }}.Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ARCH=${{ inputs.arch }}
            FEATURES=${{ inputs.features }}
            VERSION=${{ env.version }}
            APP_NAME=${{ inputs.app_name }}
            APP_EXEC=${{ inputs.app_exec }}
          tags: |
            ${{ secrets.DOCKER_PROVIDER }}/${{ secrets.DOCKER_REPO }}/${{ inputs.image_name }}:${{ env.version }}
            ${{ env.tag_alias }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
