---
name: Build docker images on-demand

on:
  workflow_call:
    secrets:
      DOCKER_PROVIDER:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
    inputs:
      toolchain:
        type: string
        description: 'Rust toolchain'
        default: nightly-2022-05-01
      arch:
        type: string
        default: x86-64
      features:
        type: string
        default: safe
      version:
        type: string
        default: v0.32.12_testnet-dibbler_20220808_leet
      image_name:
        type: string
        default: tari_sha3_miner
      app_name:
        type: string
        default: sha3_miner
      app_exec:
        type: string
        default: tari_miner
      dockercontext:
        type: string
        default: tari
      dockerfile:
        type: string
        default: tarilabs
      platforms:
        type: string
        default: linux/amd64
        # linux/arm64, linux/amd64
      tags:
        type: string
        description: 'On-demand build description'

jobs:
  docker_build:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest

    steps:
      - name: checkout tari
        uses: actions/checkout@v3
        with:
          path: tari
          submodules: recursive

      - name: checkout tari-launchpad
        uses: actions/checkout@v3
        with:
          # repository: tari-project/tari-launchpad
          repository: leet4tari/tari-launchpad
          ref: build-leet-tari-test
          path: tari-launchpad

      - name: prep work
        shell: bash
        run: |
          mkdir -p tari/buildtools/docker_rig
          cp -v tari-launchpad/docker_rig/start_tari_app.sh tari/buildtools/docker_rig/start_tari_app.sh

      - name: Login to Docker Image Provider
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_PROVIDER }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU for Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker image build and push
        uses: docker/build-push-action@v3
        with:
          context: ./${{ inputs.dockercontext }}/
          file: ./tari-launchpad/docker_rig/${{ inputs.dockerfile }}.Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ARCH=${{ inputs.arch }}
            FEATURES=${{ inputs.features }}
            VERSION=${{ inputs.version }}
            APP_NAME=${{ inputs.app_name }}
            APP_EXEC=${{ inputs.app_exec }}
          tags: |
            ${{ secrets.DOCKER_PROVIDER }}/${{ secrets.DOCKER_REPO }}/${{ inputs.image_name }}:${{ inputs.version }}
