---
name: Build docker images - Test

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "build-leet-*"
  schedule:
    - cron: "05 00 * * *"
  workflow_dispatch:
    inputs:
      toolchain:
        type: string
        description: 'Rust toolchain'
      version:
        type: string
        description: 'build tag/version'
      tag_alias:
        type: string
        description: 'build tag alias'
      platforms:
        description: 'Docker build platform(s)'
        default: linux/amd64
        required: true
        type: choice
        options:
        - linux/amd64
        - linux/arm64
        - linux/arm64, linux/amd64

env:
  toolchain_default: nightly-2022-05-01

jobs:
  envs_setup:
    runs-on: ubuntu-latest
    outputs:
      toolchain: ${{ steps.set_toolchain.outputs.toolchain }}
      matrix: ${{ steps.set_matrix.outputs.matrix }}

    steps:
      - name: Set toolchain
        id: set_toolchain
        run: |
          if [ -z "${{ inputs.toolchain }}" ]; then
            echo "Using default"
            btoolchain=${{ env.toolchain_default }}
          else
            echo "Using provided input"
            btoolchain=${{ inputs.toolchain }}
          fi
          echo "Rust toolchain - ${btoolchain} ."
          echo "toolchain=${btoolchain}" >> $GITHUB_ENV

      - name: checkout tari-launchpad
        uses: actions/checkout@v3
        with:
          # repository: tari-project/tari-launchpad
          repository: leet4tari/tari-launchpad
          ref: build-leet-tari-test-cache
          path: tari-launchpad

      - name: Set Matrix
        id: set_matrix
        run: |
          matrix=$( jq -s -c .[] tari-launchpad/tarisuite.json )

          echo $matrix
          echo $matrix | jq .
          #echo "::set-output name=matrix::$matrix"
          echo "matrix=${matrix}" >> $GITHUB_ENV

  builds_run:
    needs: envs_setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.envs_setup.outputs.matrix) }}
    uses: ./.github/workflows/build_dockers_workflow.yml
    secrets: inherit
    with:
      image_name: ${{ matrix.image_name }}
      app_name: ${{ matrix.app_name }}
      app_exec: ${{ matrix.app_exec }}
      toolchain: ${{ needs.envs_setup.outputs.toolchain }}
      platforms: ${{ inputs.platforms }}
      version: ${{ inputs.version }}
      tag_alias: ${{ inputs.tag_alias }}
