---
name: Integration testing

'on':
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - 'leet-integration_tests*'
  pull_request:
    types: [opened]

env:
  toolchain: nightly-2022-05-01

jobs:
  builds_run:
  uses: ./.github/workflows/build_binaries_workflow.yml

  integration:
    name: integration
    runs-on: ubuntu-latest
    steps:
      - name: npm ci and lint
        shell: bash
        working-directory: integration_tests
        run: |
          node -v
          npm ci
          npm run check-fmt
          npm run lint

      - name: run cucumber scenarios
        shell: bash
        working-directory: integration_tests
        run: |
          mkdir -p cucumber_output
          node_modules/.bin/cucumber-js --tags "not @long-running and not @broken and not @wallet-ffi" --format json:cucumber_output/tests.cucumber --exit --retry 2 --retryTagFilter "@flaky and not @broken"

      - name: generate report
        if: always()
        shell: bash
        working-directory: integration_tests
        run: |
          node ./generate_report.js

      - name: store test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test results
          path: |
            integration_tests/cucumber_output
            integration_tests/temp/reports

      - name: run ffi wallet cucumber scenarios
        if: ${{ inputs.tests_ffi == 'true' }}
        shell: bash
        working-directory: integration_tests
        run: |
          mkdir -p cucumber_output
          node_modules/.bin/cucumber-js --tags "not @long-running and not @broken and not @flaky and @wallet-ffi" --format json:cucumber_output/tests_ffi.cucumber --exit

      - name: generate ffi report
        if: ${{ inputs.tests_ffi == 'true' }}
        shell: bash
        working-directory: integration_tests
        run: |
          cd integration_tests
          node ./generate_report.js "cucumber_output/tests_ffi.cucumber" "temp/reports/cucumber_ffi_report.html"
