---
name: Integration testing

'on':
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - 'leet-integration_tests*'
  pull_request:
    types: [opened]

env:
  toolchain: nightly-2022-05-01

jobs:
  builds_run:
    uses: ./.github/workflows/build_binaries_workflow.yml
    with:
#      build_binaries: "tari_base_node tari_console_wallet tari_merge_mining_proxy tari_miner tari_wallet_ffi"
      build_binaries: "tari_base_node tari_console_wallet tari_merge_mining_proxy tari_miner"

  integration:
    name: integration
    needs: builds_run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: npm ci and lint
        shell: bash
        working-directory: integration_tests
        run: |
          node -v
          npm ci
          npm run check-fmt
          npm run lint
          cd ../clients/base_node_grpc_client
          npm install
          cd ../wallet_grpc_client
          npm install

      - name: Cache cargo files and outputs
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "tari-binaries-builds"
          env-vars: ""

      - name: Debug target build
        continue-on-error: true
        shell: bash
        run: |
          ls -la $GITHUB_WORKSPACE/target
          du -sh $GITHUB_WORKSPACE/target

      - name: run cucumber scenarios
        timeout-minutes: 30
        shell: bash
        working-directory: integration_tests
        run: |
          mkdir -p cucumber_output
          node_modules/.bin/cucumber-js --profile "ci" --tags "not @wallet-ffi" \
            --format json:cucumber_output/tests.cucumber --exit \
            --retry 2 --retry-tag-filter "@flaky and not @broken"

      - name: generate report
        if: always()
        shell: bash
        working-directory: integration_tests
        run: |
          node ./generate_report.js

      - name: store test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test results
          path: |
            integration_tests/cucumber_output
            integration_tests/temp/reports

      - name: run ffi wallet cucumber scenarios
        if: ${{ inputs.tests_ffi == 'true' }}
        shell: bash
        working-directory: integration_tests
        run: |
          mkdir -p cucumber_output
          node_modules/.bin/cucumber-js --profile "ci"  --tags "@wallet-ffi" \
            --format json:cucumber_output/tests_ffi.cucumber --exit \
            --retry 2 --retry-tag-filter "@flaky and not @broken"

      - name: generate ffi report
        if: ${{ inputs.tests_ffi == 'true' }}
        shell: bash
        working-directory: integration_tests
        run: |
          node ./generate_report.js "cucumber_output/tests_ffi.cucumber" "temp/reports/cucumber_ffi_report.html"

      - name: store test results
        uses: actions/upload-artifact@v3
        if: ${{ inputs.tests_ffi == 'true' }}
        #if: always()
        with:
          name: test results
          path: |
            integration_tests/cucumber_output
            integration_tests/temp/reports
