---
# Build a new set of libraries when a new tag containing 'libwallet' is pushed
name: Build libwallet

on:
  push:
    branches:
      - "libwallet-*"
      - build-leet-testnet-dibbler-libwallet
    tags:
      - "libwallet-*"
  schedule:
    - cron: "05 00 * * *"
  workflow_dispatch:
    inputs:
      customTag:
        description: "Development Tag"
        required: true
        default: "development-tag"

env:
  toolchain: nightly-2022-05-01

jobs:
  android:
    name: Build Android
    strategy:
      fail-fast: false
      matrix:
        build: [
          x86_64-linux-android,
          aarch64-linux-android,
        ]
#          armv7-linux-androideabi
          # todo: once determined if this 32bit arm build is still required
          # then make necessary changes to tari comms (metrics fully optional)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
          toolchain: ${{ env.toolchain }}
          target: ${{ matrix.build }}
          override: true

      - name: Build libwallet libraries
        uses: actions-rs/cargo@v1
        env:
          CFLAGS: "-DMDB_USE_ROBUST=0"
        with:
          use-cross: true
          command: build
          args: >
            --release -p tari_wallet_ffi
            --target=${{ matrix.build }}

      - name: Prepare libwallet libraries
        shell: bash
        run: |
          ls -alht target/${{ matrix.build }}/release/
          mkdir -p "${{ runner.temp }}/libwallet"
          target_temp=${{ matrix.build }}
          # Strip '-linux-android'
          target_platform=$(echo "${target_temp/-linux-android*/}")
          echo "target_platform=${target_platform}" >> $GITHUB_ENV
          cp -v target/${{ matrix.build }}/release/libtari_wallet_ffi.a "${{ runner.temp }}/libwallet/libtari_wallet_ffi.${target_platform}.a"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: libwallet-android-${{ env.target_platform }}
          path: ${{ runner.temp }}/libwallet

  ios:
    name: Build iOS

    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Rust toolchain (x86_64)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
          toolchain: ${{ env.toolchain }}
          target: x86_64-apple-ios
          override: true

      - name: Setup Rust toolchain (aarch64)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
          toolchain: ${{ env.toolchain }}
          target: aarch64-apple-ios
          override: true

      - name: Install macOS dependencies
        run: brew install cmake zip

      - name: Build libwallet libraries
        run: |
          mkdir -p MobileWallet/TariLib/
          cd base_layer/wallet_ffi
          mv ios.config build.config
          ./mobile_build.sh || exit 1
          ls -alht $GITHUB_WORKSPACE/MobileWallet/TariLib/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: libwallet-ios
          path: ${{ github.workspace }}/MobileWallet/TariLib/libtari_wallet_ffi.a

  create-release:
    runs-on: ubuntu-latest
    needs: [android, ios]
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          path: libwallet

      - name: Debugging
        shell: bash
        run: ls -alhtR
        working-directory: libwallet

      - name: Sync to S3
        if: ${{ startsWith(github.ref, 'refs/tags/libwallet') }}
        continue-on-error: true # Don't break if s3 upload fails
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # optional: defaults to us-east-1
          SOURCE_DIR: "$GITHUB_WORKSPACE/libwallet"
          DEST_DIR: "libwallet"

      - name: Create release
        if: ${{ startsWith(github.ref, 'refs/tags/libwallet') }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "libwallet*/**/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: true
